classdef OperationModes
    enumeration 
            Unimplemented, ...
            PPM, ...
            PVM, ...
            HMM, ...
            CSP, ...
            CSV, ...
            CST
    end
end
