% -------------------------------------------------------------------
%  Generated by MATLAB on 20-Oct-2021 12:00:08
%  MATLAB version: 9.8.0.1323502 (R2020a)
% -------------------------------------------------------------------
                                

H_ECMotor = Simulink.Parameter;
H_ECMotor.Value = 0.109;
H_ECMotor.CoderInfo.StorageClass = 'Auto';
H_ECMotor.Description = ['Terminal inductance', char(10), '', char(10), '' ...
                         'Reference:', char(10), 'https://www.maxongrou' ...
                         'p.com/maxon/view/product/607325'];
H_ECMotor.DataType = 'auto';
H_ECMotor.Min = [];
H_ECMotor.Max = [];
H_ECMotor.DocUnits = 'mH';

H_ECMotorCopy = Simulink.Parameter;
H_ECMotorCopy.Value = 0.109;
H_ECMotorCopy.CoderInfo.StorageClass = 'Auto';
H_ECMotorCopy.Description = ['Terminal inductance', char(10), '', char(10), '' ...
                             'Reference:', char(10), 'https://www.maxon' ...
                             'group.com/maxon/view/product/607325'];
H_ECMotorCopy.DataType = 'auto';
H_ECMotorCopy.Min = [];
H_ECMotorCopy.Max = [];
H_ECMotorCopy.DocUnits = 'mH';

I_ECMotor = Simulink.Parameter;
I_ECMotor.Value = 12.1;
I_ECMotor.CoderInfo.StorageClass = 'Auto';
I_ECMotor.Description = ['Nominal current (max. continuous current)', char(10), '' ...
                         'Min = No load current', char(10), 'Max = Stal' ...
                         'l current', char(10), '', char(10), 'Referenc' ...
                         'e:', char(10), 'https://www.maxongroup.com/ma' ...
                         'xon/view/product/607325'];
I_ECMotor.DataType = 'auto';
I_ECMotor.Min = 0.83;
I_ECMotor.Max = 166;
I_ECMotor.DocUnits = 'A';

R_ECMotor = Simulink.Parameter;
R_ECMotor.Value = 0.109;
R_ECMotor.CoderInfo.StorageClass = 'Auto';
R_ECMotor.Description = ['Terminal resistance', char(10), '', char(10), '' ...
                         'Reference:', char(10), 'https://www.maxongrou' ...
                         'p.com/maxon/view/product/607325'];
R_ECMotor.DataType = 'auto';
R_ECMotor.Min = [];
R_ECMotor.Max = [];
R_ECMotor.DocUnits = ['', char(26), ''];

T_ECMotor = Simulink.Parameter;
T_ECMotor.Value = 1010;
T_ECMotor.CoderInfo.StorageClass = 'Auto';
T_ECMotor.Description = ['Nominal torque (max. continuous torque)', char(10), '' ...
                         'Max = Stall torque', char(10), '', char(10), '' ...
                         'Reference:', char(10), 'https://www.maxongrou' ...
                         'p.com/maxon/view/product/607325'];
T_ECMotor.DataType = 'auto';
T_ECMotor.Min = 0;
T_ECMotor.Max = 13400;
T_ECMotor.DocUnits = 'mN*m';

V_ECMotor = Simulink.Parameter;
V_ECMotor.Value = 18;
V_ECMotor.CoderInfo.StorageClass = 'Auto';
V_ECMotor.Description = ['Nominal voltage', char(10), '', char(10), 'Re' ...
                         'ference:', char(10), 'https://www.maxongroup.' ...
                         'com/maxon/view/product/607325'];
V_ECMotor.DataType = 'auto';
V_ECMotor.Min = [];
V_ECMotor.Max = [];
V_ECMotor.DocUnits = 'V';

eta_ECMotor = Simulink.Parameter;
eta_ECMotor.Value = 0.86;
eta_ECMotor.CoderInfo.StorageClass = 'Auto';
eta_ECMotor.Description = ['Max. efficiency', char(10), '', char(10), '' ...
                           'Reference:', char(10), 'https://www.maxongr' ...
                           'oup.com/maxon/view/product/607325'];
eta_ECMotor.DataType = 'auto';
eta_ECMotor.Min = [];
eta_ECMotor.Max = [];
eta_ECMotor.DocUnits = '';

n_ECMotor = Simulink.Parameter;
n_ECMotor.Value = 1770;
n_ECMotor.CoderInfo.StorageClass = 'Auto';
n_ECMotor.Description = ['Nominal speed', char(10), 'Max = no load spee' ...
                         'd', char(10), '', char(10), 'Reference:', char(10), '' ...
                         'https://www.maxongroup.com/maxon/view/product' ...
                         '/607325'];
n_ECMotor.DataType = 'auto';
n_ECMotor.Min = 0;
n_ECMotor.Max = 2100;
n_ECMotor.DocUnits = 'rpm';

