function out1 = JointInvKin(L1,L2,L3,L4,h1,y1,y2,y3,y4)
%JOINTINVKIN
%    OUT1 = JOINTINVKIN(L1,L2,L3,L4,H1,Y1,Y2,Y3,Y4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    12-Jan-2022 22:31:37

t2 = L1.*y1;
t3 = L1.*y2;
t4 = L1.^2;
t5 = y1.^2;
t6 = 1.0./L1;
t7 = 1.0./L2;
t8 = 1.0./L3;
t9 = -y3;
t10 = -t3;
t11 = -t5;
t12 = t6.*y1;
t13 = t9+y2;
t14 = asin(t12);
t15 = t4+t11;
t16 = t8.*t13;
t17 = asin(t16);
t18 = sqrt(t15);
t19 = h1.*t18;
t20 = t2+t10+t19;
t21 = t6.*t7.*t20;
t22 = asin(t21);
out1 = [t14,-t14-t22-pi./2.0,-t17+t22,t17-asin((y3-y4)./L4)];
