function COM_est = JointCOMTraj(L1,L2,L3,h1,l1,l2,l3,l4,m1,m2,m3,m4,theta1,theta2,theta3,theta4)
%JOINTCOMTRAJ
%    COM_EST = JOINTCOMTRAJ(L1,L2,L3,H1,L1,L2,L3,L4,M1,M2,M3,M4,THETA1,THETA2,THETA3,THETA4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    12-Jan-2022 22:31:37

t2 = cos(theta1);
t3 = sin(theta1);
t4 = theta1+theta2;
t12 = m1+m2+m3+m4;
t5 = L1.*t2;
t6 = L1.*t3;
t7 = h1.*t2;
t8 = cos(t4);
t9 = h1.*t3;
t10 = sin(t4);
t11 = t4+theta3;
t19 = 1.0./t12;
t13 = cos(t11);
t14 = sin(t11);
t15 = t11+theta4;
t16 = L2.*t8;
t17 = L2.*t10;
t18 = -t5;
COM_est = [-t19.*(m2.*(t9+t18+l2.*t10)+m4.*(t9+t17+t18+L3.*t14+l4.*sin(t15))+m3.*(t9+t17+t18+l3.*t14)-l1.*m1.*t2),t19.*(m4.*(t6+t7+t16+L3.*t13+l4.*cos(t15))+m2.*(t6+t7+l2.*t8)+m3.*(t6+t7+t16+l3.*t13)+l1.*m1.*t3)];
