function theta = JointTrajFit(t,a,t_f,theta_f,theta_i,theta__dot_f,theta__dot_i,theta__ddot_i)
%JOINTTRAJFIT
%    THETA = JOINTTRAJFIT(T,A,T_F,THETA_F,THETA_I,THETA__DOT_F,THETA__DOT_I,THETA__DDOT_I)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    12-Jan-2022 22:31:38

t2 = t_f.^2;
t3 = t_f.^5;
t4 = t2.*theta__ddot_i;
theta = theta_i+t.*theta__dot_i+a.*t.^5+(t.^2.*theta__ddot_i)./2.0+(t.^4.*1.0./t2.^2.*(t4-theta_f.*6.0+theta_i.*6.0-a.*t3.*4.0+t_f.*theta__dot_f.*2.0+t_f.*theta__dot_i.*4.0))./2.0-t.^3.*1.0./t_f.^3.*(t4-theta_f.*4.0+theta_i.*4.0-a.*t3+t_f.*theta__dot_f+t_f.*theta__dot_i.*3.0);
