% -------------------------------------------------------------------
%  Generated by MATLAB on 29-Dec-2021 10:44:32
%  MATLAB version: 9.8.0.1323502 (R2020a)
% -------------------------------------------------------------------
                                   
x520886_ICont = Simulink.Parameter;
x520886_ICont.Value = 15;
x520886_ICont.CoderInfo.StorageClass = 'Auto';
x520886_ICont.Description = ['Continuous output current', char(10), 'Fo' ...
                             'r more information, visit EPOS4 Applicati' ...
                             'on Notes Collection Edition 2021-03'];
x520886_ICont.DataType = 'double';
x520886_ICont.Min = -30;
x520886_ICont.Max = 30;
x520886_ICont.DocUnits = 'A';

x520886_TsCur = Simulink.Parameter;
x520886_TsCur.Value = 0.04;
x520886_TsCur.CoderInfo.StorageClass = 'Auto';
x520886_TsCur.Description = ['During a movement within a drive system, ' ...
                             'forces and/or torques must be controlled.' ...
                             '', char(10), 'Therefore, as a principal r' ...
                             'egulation structure, EPOS4 offers current' ...
                             '-based control', char(10), 'For more info' ...
                             'rmation, visit EPOS4 Application Notes Co' ...
                             'llection Edition 2021-03'];
x520886_TsCur.DataType = 'double';
x520886_TsCur.Min = [];
x520886_TsCur.Max = [];
x520886_TsCur.DocUnits = 'ms';

x520886_fDIncrEnc = Simulink.Parameter;
x520886_fDIncrEnc.Value = 6.25E+6;
x520886_fDIncrEnc.CoderInfo.StorageClass = 'Auto';
x520886_fDIncrEnc.Description = ['', char(10), 'For '];
x520886_fDIncrEnc.DataType = 'double';
x520886_fDIncrEnc.Min = 0;
x520886_fDIncrEnc.Max = 6.25E+6;
x520886_fDIncrEnc.DocUnits = 'Hz';

