% onemax
function fitnessVals = fitnessFunc(Len1,Len2,Len3,h1,...
                           l1,l2,l3,l4,...
                           m1,m2,m3,m4,...
                           lb,ub,COMxmax,tfmin,... % constraints
                           COMRef,thetas,taus,tf,popSize)
        COM_est = COMTrajectory(Len1,Len2,Len3,h1,...
                                   l1,l2,l3,l4,...
                                   m1,m2,m3,m4,...
                                   thetas(:,1), thetas(:,2), thetas(:,3), thetas(:,4));
%         COMRefMat = repmat(COMRef,size(COM_est,1),1);
%         COMerr = COM_est-COMRefMat;
        COMerr = COM_est-COMRef;
        if all(repmat(lb,popSize,1)<[thetas taus],'all') ...
                && all([thetas taus]<repmat(ub,popSize,1),'all') ...
                && COM_est(1)<=COMxmax
%         if all(repmat(lb(1:4),popSize,1)<thetas,'all') ... 
%                 && all(thetas<repmat(ub(1:4),popSize,1),'all') ...                  
            fitnessVals = 1./(2*sqrt(dot(COMerr,COMerr,2)) + 1);
        else
            fitnessVals = 1./(2*sqrt(dot(COMerr,COMerr,2)) + 100);
        end